server:
  port: 8003

mybatis:
  type-aliases-package: com.shen.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  application:
    name: springCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456


# Eureka的配置，服务注册到哪里
eureka:
  client:
   service-url:
     # 注册中心地址7001-7003
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-8003 #修改eureka上的默认描述信息！


#info配置
info:
  app.name: youdong-springcloud
  company.name: blog.youdong.com

