server:
  port: 3344

spring:
  application:
    name: springcloud-config-server

    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/outlaw-huang-san/springcloud.git  #https的，不是ssh


# 通过 config-server, 可以连接到git，访问其中的资源以及配置~
